### ISSUE TITLE
Make bitshift.crawler.crawl executable as a module.

### ISSUE THREAD

**Issue by benattal** [earwig/bitshift#26]
- [x] Run the crawler via `py python -m bitshift.crawler.crawl`
- [x] Add parser initialization statements/calls.

**Comment by sevko** [comment]
@breuckelen , status on this?

**Comment by benattal** [comment]
I made it so the crawl function starts up the parsers.  I didn't add any calls to the actual parse function -- didn't you do that @sevko?

**Comment by benattal** [comment]
If you did, then we should be good to go.

**Comment by earwig** [comment]
Yes.
