### ISSUE TITLE
Generate real search results

### ISSUE THREAD

**Issue by benattal** [earwig/bitshift#27]
- call getQuery() from javascript, which sends the query string to `/search.json` route and generates the results on the page
- make progress bar to show how much of the database has been searched

**Comment by earwig** [comment]
A progress bar would be _very_ non-trivial. Use some spinny wheel like [this one](http://css-tricks.com/css-page-loader/) for now and leave that for later, if we can ever do it.

**Comment by benattal** [comment]
@sevko, note that in the route you access with getQuery, you are going to have to turn the code field in codelet into formatted html, using pygments, before returning it.

**Comment by earwig** [comment]
The above is fixed.

**Comment by sevko** [comment]
Completed in 21067ef .
