### ISSUE TITLE
Create a demo video.

### ISSUE THREAD

**Issue by sevko** [earwig/bitshift#40]
Create a demo video for **bitshift**.

Ideas:
- ~~Background music: **Beethoven's 5th Symphony**.~~
- ~~Fast paced features display.~~

**Comment by earwig** [comment]
I have some solid ideas for how I could create this, but the issue is time. When do we actually need it by?

**Comment by benattal** [comment]
Can we spend some time together on this?

**Comment by earwig** [comment]
It's a really tight schedule. This weekend is shot because of prom (and we probably won't be done by then anyway), and the weekend after... is that too late?

**Comment by sevko** [comment]
We'll talk tomorrow during SoftDev. @earwig and I spoke briefly about our idea as it stands and scheduling, and we have some issues to iron out.

**Comment by earwig** [comment]
http://vimeo.com/ear/bitshift
