### ISSUE TITLE
Key maps for navigating search results.

### ISSUE THREAD

**Issue by benattal** [earwig/bitshift#47]
Shortcut keys:   
- [x] `j`, `k` : switch between results.
- [x] `h`, `l` : switch between matches.
- [ ] `?` : display keyboard shortcut help.

**Comment by sevko** [comment]
@breuckelen , you should handle `h` and `l`, because we need to expose the symbol-scrolling functions in `createResult()` in `index.js` and you'll know best how to do it. @3fe6b2e committed all of the necessary infrastructure for adding a new keymap, in `resultsHotkeys()`.

**Comment by benattal** [comment]
I'll do my best to get this finished by tonight along with some of my other issues.

**Comment by benattal** [comment]
Pushed to feature/style

**Comment by benattal** [comment]
Haven't done `?` keymap yet

**Comment by sevko** [comment]
I'll handle it, after I run a design by @breuckelen and @earwig .
