### ISSUE TITLE
Register a domain.

### ISSUE THREAD

**Issue by sevko** [earwig/bitshift#52]
Rent a domain and link it to our server.

**Comment by earwig** [comment]
Assigning back to @sevko, since I believe he will be making the actual registration?

**Comment by sevko** [comment]
@earwig is administrating the server, so I assumed he would.

**Comment by earwig** [comment]
Easier for you to buy it, I think. I can just add the A record once you get it. Or you can. I'm not sure how that works.

**Comment by yuna9** [comment]
I would suggest that @earwig add the A record. While @sevko can buy the domain, it's far better to use something like DigitalOcean or Cloudflare to manage the DNS records. Do this by setting the NS records in the registrar to ns[1-3].digitalocean.com or the Cloudflare servers you were assigned.

**Comment by earwig** [comment]
thank u digitalocean tech support

**Comment by yuna9** [comment]
bitshift.com is not available but bitshif.tt is available.

**Comment by earwig** [comment]
Other options:
- bitshift.in
- bitshift.info
- bitshift.link
- bitshift.it (my choice)

**Comment by sevko** [comment]
My choices in descending preference:
- bitshift.it
- bitshift.in

**Comment by benattal** [comment]
^^

**Comment by earwig** [comment]
Okay. @sevko, can you try to buy bitshift.it?

**Comment by sevko** [comment]
Status?

**Comment by earwig** [comment]
It works!

http://bitshift.it/
