### ISSUE TITLE
Add a developers page for the API.

### ISSUE THREAD

**Issue by sevko** [earwig/bitshift#56]
Add a developers page, which will document our API.

**Comment by sevko** [comment]
@earwig , are you willing to implement this?

Note that it overlaps heavily with #73 ; I think the query language should be documented in `/docs`, and that `/developers` should currently retain mostly empty. `/developers` will basically contain a description of our API, which doesn't have much substance and doesn't need any explanations beyond how queries work.

**Comment by earwig** [comment]
I can do it, but it won't be too soon.

**Comment by sevko** [comment]
Alright. I'm nearly finished with #73 , so you'll only have to add a brief description about how hand-written queries work (with the escaped quote weirdness).

**Comment by earwig** [comment]
I'll look into it after #74 and various misc fixes (text-only searching is broken right now).
