### ISSUE TITLE
Ruby class parsing (sometimes) yields incorrect results.

### ISSUE THREAD

**Issue by benattal** [earwig/bitshift#62]

**Comment by earwig** [comment]
If this includes adding things like `>=` and `[]`, then good - otherwise, make note of that too.

**Comment by benattal** [comment]
> =, [], ==, etc. are all considered functions in ruby.  You can define each of these and how they behave on specific classes.  Closing this issue.

**Comment by earwig** [comment]
Who would ever want to search for ruby code that uses `>=`?

**Comment by earwig** [comment]
The point is, there's a lot of them, and it potentially pollutes the database and makes it slower for other searches.

**Comment by benattal** [comment]
Ben... people who write ruby code define these methods (as I listed: >=, ==, ===, <<) on different objects all the time.  The point of bitshift is to search for functions that are defined and used.  These fall under that category for ruby.
