### ISSUE TITLE
humans.txt

### ISSUE THREAD

**Issue by earwig** [earwig/bitshift#75]

**Comment by legoktm** [comment]
humans.txt is silly and has no purpose whatsoever.

**Comment by yuna9** [comment]
stfu and stop being a spoilsport :~)

**Comment by legoktm** [comment]
If you want to be hip and cool, create an androids.txt or something even sillier.

**Comment by earwig** [comment]
no u

**Comment by yuna9** [comment]
gtfo @legoktm https://encrypted.google.com/search?hl=en&as_q=androids.txt

**Comment by legoktm** [comment]
plz https://duckduckgo.com/?q=androids.txt

**Comment by earwig** [comment]
WONTFIX you nerds

especially @legoktm
